name: sudoku
description: an new Sudoku Flutter application.
homepage: https://github.com/einsitang/sudoku-flutter
# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.4.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '^3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: '^0.18.1'
  # sudoku_dart: '^1.2.0'
  logger: "^2.4.0"
  sprintf: "^7.0.0"
  scoped_model: "^2.0.0"
  modal_bottom_sheet: "^3.0.0"
  hive: "^2.2.3"
  hive_flutter: "^1.1.0"
  cupertino_icons: ^1.0.5
  url_launcher: ^6.1.7
  just_audio: ^0.9.39
  camera_android_camerax: 0.6.5
  camera: 0.11.0+1
  path_provider: ^2.1.3
  path: ^1.9.0
  image: ^4.2.0
  yaml: ^3.1.2
  tflite_flutter: ^0.11.0
  opencv_dart: 1.2.3

  # firebase_core: ^3.3.0
  # firebase_crashlytics: ^4.0.4
  # firebase_analytics: ^11.2.1
  # firebase_performance: ^0.10.0+4

  ffi: ^2.1.3
  flutter_animate: ^4.5.2
  flutter_svg: ^2.0.10+1
  simple_shadow: ^0.3.1

  flutter_remix: 0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.3
  ffigen: ^14.0.1

flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/image/
    - assets/svg/
    - assets/audio/
    - assets/audio/speak/
    - assets/tf_model/sudoku/
    - assets/tf_model/digits/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Summary Notes
      fonts:
        - asset: assets/fonts/Summary-Notes.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf



ffigen:
  # 生成文件的路径
  output: lib/native/nativefl.dart
  # 生成文件的 class name
  name: Nativefl
  # 生成的描述
  description: Native bindings for nativefl
  headers:
    entry-points:
      # 头文件，根据库文件会生成具体的方法
      - src/libsudoku.h
